// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fonnidefxfrzwtaabacn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvbm5pZGVmeGZyend0YWFiYWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjMzMzUsImV4cCI6MjA2NjA5OTMzNX0.Z3nqL2BT8vSTup6bEccY_KVh-Rkj4lPUZequJMG50tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);